/**
 * Robot data for Storybook examples
 * Used across multiple table stories
 */

export interface Robot {
  id: string;
  name: string;
  model: string;
  application: string;
  facility: string;
  uptime: number;
  status: 'Active' | 'Maintenance' | 'Offline';
}

export const robots: Robot[] = [
  {
    id: 'MAiRA-001',
    name: 'MAiRA Alpha',
    model: 'MAiRA',
    application: 'Palletizing',
    facility: 'Munich Plant A',
    uptime: 99.8,
    status: 'Active',
  },
  {
    id: 'LARA-002',
    name: 'LARA Beta',
    model: 'LARA',
    application: 'Machine Tending',
    facility: 'Stuttgart Factory',
    uptime: 98.5,
    status: 'Active',
  },
  {
    id: 'MAV-003',
    name: 'MAV Gamma',
    model: 'MAV',
    application: 'Logistics',
    facility: 'Berlin Warehouse',
    uptime: 97.2,
    status: 'Maintenance',
  },
  {
    id: '4NE1-004',
    name: '4NE1 Delta',
    model: '4NE1',
    application: 'Quality Inspection',
    facility: 'Hamburg Line B',
    uptime: 99.1,
    status: 'Active',
  },
  {
    id: 'MAiRA-005',
    name: 'MAiRA Epsilon',
    model: 'MAiRA',
    application: 'Welding',
    facility: 'Metzingen HQ',
    uptime: 99.5,
    status: 'Active',
  },
  {
    id: 'MiPA-006',
    name: 'MiPA Zeta',
    model: 'MiPA',
    application: 'Assistance',
    facility: 'Frankfurt Office',
    uptime: 99.9,
    status: 'Active',
  },
  {
    id: 'LARA-007',
    name: 'LARA Eta',
    model: 'LARA',
    application: 'Assembly',
    facility: 'Munich Plant B',
    uptime: 96.3,
    status: 'Active',
  },
  {
    id: 'MAiRA-008',
    name: 'MAiRA Theta',
    model: 'MAiRA',
    application: 'Packaging',
    facility: 'Stuttgart Factory',
    uptime: 98.7,
    status: 'Active',
  },
  {
    id: 'MAV-009',
    name: 'MAV Iota',
    model: 'MAV',
    application: 'Transport',
    facility: 'Berlin Warehouse',
    uptime: 94.1,
    status: 'Offline',
  },
  {
    id: '4NE1-010',
    name: '4NE1 Kappa',
    model: '4NE1',
    application: 'Inspection',
    facility: 'Hamburg Line A',
    uptime: 99.4,
    status: 'Active',
  },
  {
    id: 'MAiRA-011',
    name: 'MAiRA Lambda',
    model: 'MAiRA',
    application: 'Sorting',
    facility: 'Munich Plant A',
    uptime: 97.8,
    status: 'Active',
  },
  {
    id: 'LARA-012',
    name: 'LARA Mu',
    model: 'LARA',
    application: 'Polishing',
    facility: 'Cologne Plant',
    uptime: 98.2,
    status: 'Maintenance',
  },
  {
    id: 'MiPA-013',
    name: 'MiPA Nu',
    model: 'MiPA',
    application: 'Collaboration',
    facility: 'Dresden Lab',
    uptime: 99.6,
    status: 'Active',
  },
  {
    id: 'MAV-014',
    name: 'MAV Xi',
    model: 'MAV',
    application: 'Delivery',
    facility: 'Leipzig Center',
    uptime: 95.9,
    status: 'Active',
  },
  {
    id: '4NE1-015',
    name: '4NE1 Omicron',
    model: '4NE1',
    application: 'Testing',
    facility: 'Metzingen HQ',
    uptime: 99.0,
    status: 'Active',
  },
  {
    id: 'MAiRA-016',
    name: 'MAiRA Pi',
    model: 'MAiRA',
    application: 'Deburring',
    facility: 'Stuttgart Factory',
    uptime: 98.4,
    status: 'Active',
  },
  {
    id: 'LARA-017',
    name: 'LARA Rho',
    model: 'LARA',
    application: 'Grinding',
    facility: 'Munich Plant B',
    uptime: 97.1,
    status: 'Offline',
  },
  {
    id: 'MAV-018',
    name: 'MAV Sigma',
    model: 'MAV',
    application: 'Warehousing',
    facility: 'Frankfurt Office',
    uptime: 96.8,
    status: 'Active',
  },
  {
    id: 'MiPA-019',
    name: 'MiPA Tau',
    model: 'MiPA',
    application: 'Training',
    facility: 'Berlin Warehouse',
    uptime: 99.7,
    status: 'Active',
  },
  {
    id: '4NE1-020',
    name: '4NE1 Upsilon',
    model: '4NE1',
    application: 'Measurement',
    facility: 'Hamburg Line B',
    uptime: 98.9,
    status: 'Active',
  },
  {
    id: 'MAiRA-021',
    name: 'MAiRA Phi',
    model: 'MAiRA',
    application: 'Dispensing',
    facility: 'Cologne Plant',
    uptime: 99.2,
    status: 'Active',
  },
  {
    id: 'LARA-022',
    name: 'LARA Chi',
    model: 'LARA',
    application: 'Screwing',
    facility: 'Dresden Lab',
    uptime: 97.5,
    status: 'Maintenance',
  },
  {
    id: 'MAV-023',
    name: 'MAV Psi',
    model: 'MAV',
    application: 'Picking',
    facility: 'Leipzig Center',
    uptime: 95.4,
    status: 'Active',
  },
  {
    id: '4NE1-024',
    name: '4NE1 Omega',
    model: '4NE1',
    application: 'Scanning',
    facility: 'Munich Plant A',
    uptime: 99.3,
    status: 'Active',
  },
  {
    id: 'MAiRA-025',
    name: 'MAiRA Prime',
    model: 'MAiRA',
    application: 'Coating',
    facility: 'Metzingen HQ',
    uptime: 98.8,
    status: 'Active',
  },
  {
    id: 'MiPA-026',
    name: 'MiPA Ultra',
    model: 'MiPA',
    application: 'Monitoring',
    facility: 'Frankfurt Office',
    uptime: 99.5,
    status: 'Active',
  },
];
